version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: reserva_postgres
    restart: always
    environment:
      POSTGRES_USER: reserva_user
      POSTGRES_PASSWORD: reserva_pass
      POSTGRES_DB: reserva_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
